### ISSUE TITLE
FALSE REPORT: VirusTotal reports HomeCinema.exe contains trojan malware 

### ISSUE THREAD

**Issue by dodgyb** [JerloPH/HomeCinema#7]
See report here:

https://www.virustotal.com/gui/file/11cab010759a3f6854f9fbe37648a4ab1c6b7b51436d450245c7bb27f67539ad/detection

**Comment by JerloPH** [comment]
This is probably a false report since I personally use this and Windows Defender also triggers with a virus warning. This happens whenever I try to delete an entry tho.

If you're not satisfied by this answer or is uncomfortable using this App, there's nothing I can do much unfortunately.

I will now close this issue.
